const dommy = [
    {
       department:'Computer SC',
       nameoflect:'Ololade',
       course:'Math',
       course_code:'MTH133',
       level:300,
       semester:'1rst',
       start_time:'10:30',
       end_time:'12:30',
       venue:'200cap',
       date:'23/4/2022',

    },
    {
        department:'Accounting',
        nameoflect:'Onifade',
        course:'Math',
        course_code:'MTH133',
        level:300,
        semester:'1rst',
        start_time:'10:30',
        end_time:'12:30',
        venue:'200cap',
        date:'23/4/2022'
     },
     {
        department:'Nursing',
        nameoflect:'Oladejo',
        course:'Math',
        course_code:'MTH133',
        level:300,
        semester:'1rst',
        start_time:'10:30',
        end_time:'12:30',
        venue:'200cap',
        date:'23/4/2022'
     },
     {
        department:'Nursing',
        nameoflect:'Adewale',
        course:'Math',
        course_code:'MTH133',
        level:300,
        semester:'1rst',
        start_time:'10:30',
        end_time:'12:30',
        venue:'200cap',
        date:'23/4/2022'
     },
     {
        department:'Nursing',
        nameoflect:'Adewale',
        course:'Math',
        course_code:'MTH133',
        level:300,
        semester:'1rst',
        start_time:'10:30',
        end_time:'12:30',
        venue:'200cap',
        date:'23/4/2022'
     },
     {
        department:'Nursing',
        nameoflect:'Adewale',
        course:'Math',
        course_code:'MTH133',
        level:300,
        semester:'1rst',
        start_time:'10:30',
        end_time:'12:30',
        venue:'200cap',
        date:'23/4/2022'
     },
     {
        department:'Nursing',
        nameoflect:'Adewale',
        course:'Math',
        course_code:'MTH133',
        level:300,
        semester:'1rst',
        start_time:'10:30',
        end_time:'12:30',
        venue:'200cap',
        date:'23/4/2022'
     },
     {
        department:'Nursing',
        nameoflect:'Adewale',
        course:'Math',
        course_code:'MTH133',
        level:300,
        semester:'1rst',
        start_time:'10:30',
        end_time:'12:30',
        venue:'200cap',
        date:'23/4/2022'
     },
     {
        department:'Nursing',
        nameoflect:'Adewale',
        course:'Math',
        course_code:'MTH133',
        level:300,
        semester:'1rst',
        start_time:'10:30',
        end_time:'12:30',
        venue:'200cap',
        date:'23/4/2022'
     },
     {
        department:'Nursing',
        nameoflect:'Adewale',
        course:'Math',
        course_code:'MTH133',
        level:300,
        semester:'1rst',
        start_time:'10:30',
        end_time:'12:30',
        venue:'200cap',
        date:'23/4/2022'
     }
]

export default dommy